[integration_samples.sfdc_new_contact_to_twilio_sms]
fromNumber = ""  
toNumber = ""  

[integration_samples.sfdc_new_contact_to_twilio_sms.twilioClientConfig]
accountSId = ""  
authToken = ""

[integration_samples.sfdc_new_contact_to_twilio_sms.salesforceOAuthConfig]
clientId = ""
clientSecret = ""
refreshToken = ""
refreshUrl = ""
